name: example_map_polyline
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  google_map_polyline:
    path: ../

flutter:

  uses-material-design: true
